### PR TITLE
remove unused import `streams`

### PR DESCRIPTION
**Pull request by 0atman**

### CODE REVIEW

**Comment by 0atman** [comment]
vscode has really great nim support! I didn't notice this bug in emacs.

**Comment by Tangdongle** [comment]
Hey mate, good stuff, must have missed that 100's of times in the compilation hints. Don't forget to remove those binary files, haha

**Comment by 0atman** [comment]
GAH! how did I miss that!? :laughing:

**Comment by 0atman** [comment]
trainwreck!

**Comment by 0atman** [comment]
Oh I get it. I committed using vscode for the first time. Not used to the git interface yet!

**Comment by 0atman** [comment]
Really nice Nim integration though!

**Comment by 0atman** [comment]
Continued in https://github.com/inim-repl/INim/pull/86

**Pull request closed without merging**
