### PR TITLE
Integration tests v2

### PR DESCRIPTION
**Pull request by Tangdongle**
Integration tests refactor

This should hopefully not break the Nim CI this time!

For further improvement, this can be split into more test cases, rather than having all tests running on a single instance

### CODE REVIEW

**Comment by Tangdongle** [comment]
@0atman Hey mate, I've given this another crack, far less complicated this time. Should *hopefully* have no issues with the Nim CI this time

**Comment by 0atman** [comment]
@Tangdongle NICE! The tests look great! Crashes though:

```
$ nimble build && ./inim
  Verifying dependencies for inim@0.4.7
      Info: Dependency on cligen@>= 0.9.15 already satisfied
  Verifying dependencies for cligen@0.9.46
      Info: Dependency on noise@any version already satisfied
  Verifying dependencies for noise@0.1.3
   Building inim/inim using c backend
Traceback (most recent call last)
/home/oatman/projects/INim/src/inim.nim(466) inim
/home/oatman/.nimble/pkgs/cligen-0.9.46/cligen.nim(722) cligenDoNotCollideWithGlobalVar
/home/oatman/.nimble/pkgs/cligen-0.9.46/cligen.nim(640) dispatchmain
/home/oatman/projects/INim/src/inim.nim(429) main
/home/oatman/projects/INim/src/inim.nim(71) welcomeScreen
/home/oatman/.choosenim/toolchains/nim-1.2.0/lib/pure/parsecfg.nim(565) getSectionValue
/home/oatman/.choosenim/toolchains/nim-1.2.0/lib/pure/collections/tables.nim(1865) hasKey
/home/oatman/.choosenim/toolchains/nim-1.2.0/lib/pure/collections/tables.nim(1372) hasKey
/home/oatman/.choosenim/toolchains/nim-1.2.0/lib/pure/collections/hashcommon.nim(46) rawGet
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by 0atman** [comment]
```
[Suite] INim Test Suite
  [OK] Get Nim Version
  [OK] Indent triggers

[Suite] Interface Tests
  [OK] Test Standard Syntax works
```
NICE!

**Comment by Tangdongle** [comment]
I wonder what the go-to procedure is to update config files with new keys? Bit silly to force create a config file each time a new value is added.

**Comment by Tangdongle** [comment]
I find it offensive that it segfaults if a key doesn't exist, haha

**Comment by Tangdongle** [comment]
haha, I'm totally wrong, I was loading config in the wrong place

**Comment by 0atman** [comment]
Works now, but there's an extra line inserted, is that intended?

# Master
 ```
$ inim
👑 INim 0.4.7
Nim Compiler Version 1.2.0 [Linux: amd64] at /home/oatman/.nimble/bin/nim
nim> 

Quitting INim: Goodbye!
```

# This Branch
```
$ ./inim
👑 INim 0.4.7
Nim Compiler Version 1.2.0 [Linux: amd64] at /home/oatman/.nimble/bin/nim

nim> 

Quitting INim: Goodbye!
```

**Comment by Tangdongle** [comment]
Not intentional! Forgot to get rid of that bit, nice catch thanks mate

**Comment by 0atman** [comment]
no, thank YOU :-D

**Comment by 0atman** [comment]
works for me!

**Pull request merged**
