### PR TITLE
Change indents to 2 spaces

### PR DESCRIPTION
**Pull request by Tangdongle**
Saw a PR with this a while ago, not sure where it went. 

2 spaces should be used for indentation according to NEP1 https://nim-lang.org/docs/nep1.html

### CODE REVIEW

**Comment by 0atman** [comment]
Why do I get further changes when running `nimpretty --indent:2 src/inim.nim`?

Did you use nimpretty to format this? Isn't that what we should use? I'm a beginner here.

**Comment by 0atman** [comment]
Apologies, the integration test branch I just merged ate your homework

**Comment by Tangdongle** [comment]
> Why do I get further changes when running `nimpretty --indent:2 src/inim.nim`?
> 
> Did you use nimpretty to format this? Isn't that what we should use? I'm a beginner here.

Yeah, that should be the way to do it. Forgot that existed. I'll repush

**Comment by Tangdongle** [comment]
Turns out nimpretty doesn't play nice with `with`, so nimpretty will produce different results. Updated with the new integration test code anyway

**Comment by 0atman** [comment]
Oh dear, are there any other automatic linting tools? I'm in love with `black`, python's formatting tool - I have it in my pre-commit hooks!

**Comment by Tangdongle** [comment]
Not sure, I believe `nimsuggest` is pretty accurate with it's styling advice, it might just be that nimpretty has an issue with a few commands.

**Comment by 0atman** [comment]
Does `nimsuggest` do styling advice? The word "indent" doesn't appear on https://nim-lang.org/docs/nimsuggest.html

**Comment by 0atman** [comment]
NOW we're talking.

```
nimpretty --indent:2 src/inim.nim
/home/oatman/projects/INim/src/inim.nim(4, 86) Hint: line too long [LineTooLong]
/home/oatman/projects/INim/src/inim.nim(45, 95) Hint: line too long [LineTooLong]
/home/oatman/projects/INim/src/inim.nim(58, 84) Hint: line too long [LineTooLong]
/home/oatman/projects/INim/src/inim.nim(60, 93) Hint: line too long [LineTooLong]
/home/oatman/projects/INim/src/inim.nim(67, 86) Hint: line too long [LineTooLong]
/home/oatman/projects/INim/src/inim.nim(102, 83) Hint: line too long [LineTooLong]
/home/oatman/projects/INim/src/inim.nim(263, 93) Hint: line too long [LineTooLong]
/home/oatman/projects/INim/src/inim.nim(331, 82) Hint: line too long [LineTooLong]
/home/oatman/projects/INim/src/inim.nim(432, 90) Hint: line too long [LineTooLong]
```

I don't care about line too long errors for the moment - thanks!

**Comment by 0atman** [comment]
@Tangdongle what do you mean by "nimpretty doesn't play nice with `with`"? There's no `with` in the diff of this PR

**Pull request merged**
