### PR TITLE
Fixed up broken --withTools

### PR DESCRIPTION
**Pull request by Tangdongle**
We now direct write our commands lib into embedded code so everything is shipped in nimble. 

By just including the commands module in embeddedCode, it's not bundled with the binary that nimble builds. By static reading the file, we can guarantee that we'll have access to the commands code.

### CODE REVIEW

**Comment by 0atman** [comment]
thanks @Tangdongle can you get those tests to pass? :muscle:

**Comment by Tangdongle** [comment]
Yeah, don't merge this even if tests fail. I think I just need to fiddle with some nimble options like installDirs

**Comment by 0atman** [comment]
righto, thank you! :ok_hand:

**Comment by Tangdongle** [comment]
@0atman I think I've got it. Had to restructure the folder to work around nimble's janky skipDir/installDirs stuff. Here's how I tested:
```
nimble uninstall inim
nimble install nimble install https://github.com/TangersTongle/INim.git
cd ~
inim --withTools
```
This should install v0.6.2 of inim from my repo, you can verify by checking the version # when downloading and when launching inim
When in inim, you can test by running
```
import strutils
cd()
```

I found it pretty difficult to just test the package as if I've downloaded it as an end-user, but I hope this works.

**Comment by Tangdongle** [comment]
Essentially, just ensuring that it runs with --withTools and the commands run outside of the INim directory (where I *always* tested the app itself from in the past, doh!) hopefully means that it will work

**Comment by Tangdongle** [comment]
@0atman Hey mate, do you have time to re-review this? Should be ready to merge in if it looks good on your end

**Comment by 0atman** [comment]
Don't know why I keep missing your messages, thank you @Tangdongle! :tada:

**Pull request merged**
