### PR TITLE
#93 Fix - Unable to unindent

### PR DESCRIPTION
**Pull request by Tangdongle**
Turns out setting the prompt to the include the indentation wasn't a great idea as users can't delete it. This inserts it using noiser's preloadBuffer, so users can just backspace to reduce indent

### CODE REVIEW

**Comment by Tangdongle** [comment]
Fix for https://github.com/inim-repl/INim/issues/93

**Comment by 0atman** [comment]
Thanks for all these PRs! I'll be able to look properly and test them tomorrow :ok_hand:

**Comment by 0atman** [comment]
@Tangdongle same conflict here - many thanks!

**Comment by 0atman** [comment]
Looks good, tests pass - thanks!

**Pull request merged**
